# This is a basic workflow to help you get started with Actions
name: Deploy with Capistrano

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test-staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Ruby
        run: |
          sudo git clone https://github.com/rbenv/rbenv.git /home/runner/.rbenv
          sudo apt-get update
          sudo apt-get install -y libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev
          sudo git clone https://github.com/rbenv/ruby-build.git /home/runner/.rbenv/plugins/ruby-build
          sudo chown -R runner /home/runner/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $GITHUB_PATH
          source $GITHUB_PATH
          eval "$(rbenv init -)"
          rbenv install -s `cat .ruby-version` # or specify the version you want
          gem install bundler:2.1.4
          bundle install --path vendor/bundle
        uses: miloserdow/capistrano-deploy@master
        with:
          target: staging # Defines the environment that will be used for the deployment
          enc_rsa_key_val: ${{ secrets.STAGING_RSA_ENC_KEY_VAL }}
          deploy_key: ${{ secrets.DEPLOY_STAGING_ENC_KEY }} # Name of the variable configured in Settings/Secrets of your github project